### PR TITLE
fix malformed & duplicated links in #405

### PR DESCRIPTION
**Pull request by ericseppanen**
The "Daily Rust: Iterators" link is malformed (missing the protocol `https://`).

cc: @Michael-F-Bryan

### CODE REVIEW

**Comment by ericseppanen** [comment]
I was confused when I found this because I was sure that I'd been able to follow this link from another browser. I just realized the answer: this link is listed twice!

I added another commit to remove the second copy.

**Comment by Michael-F-Bryan** [comment]
Hmm, that's strange. 

https://github.com/rust-lang/this-week-in-rust/pull/2335/commits/f52cfc3ad1ca9d0ed370414e8b89fea59eb62367 only added one copy of the link. It looks like #2335 also has a *"Merge branch 'master' into iterators"* commit where @nellshamrell brought the branch in line with `master`, so maybe it was accidentally introduced during a similar merge/rebase on another PR?

**Comment by ericseppanen** [comment]
Hmm, perhaps there should be a CI job to detect malformed and/or duplicate links?

**Comment by ericseppanen** [comment]
@nellshamrell 

> Looks like this was fixed in a previous PR. I agree, having some CI to detect malformed/dupe links would be useful. I don't have time to look into it immediately, but I would welcome a contribution from someone adding this!

I'm not sure what you mean? The bad & duplicated links still exist in the repo, as well as on the current website.

**Comment by ericseppanen** [comment]
> Looks like this was fixed in a previous PR. I agree, having some CI to detect malformed/dupe links would be useful. I don't have time to look into it immediately, but I would welcome a contribution from someone adding this!

I'm not sure what you mean? The bad & duplicated links still exist in the repo, as well as on the current website.

**Comment by nellshamrell** [comment]
Sorry about that, I forgot to deploy yesterday after merging. It's deployed now!

**Pull request closed without merging**
