### PR TITLE
project: Fluvio update

### PR DESCRIPTION
**Pull request by sehz**

### CODE REVIEW

**Comment by sehz** [comment]
@nellshamrell can you review this?

**Comment by nellshamrell** [comment]
Hi there! That issue has already been published, would it be alright if the update were included in next week's issue?

**Comment by sehz** [comment]
Sure. That works

**Comment by sehz** [comment]
@nellshamrell updated PR for 07-07 issue

**Review by nellshamrell — APPROVED** [review]
Thank you!

**Pull request merged**
