### PR TITLE
Add Rust MC in LPC 2022 event

### PR DESCRIPTION
**Pull request by ojeda**
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>

### CODE REVIEW

**Comment by ojeda** [comment]
By the way, I followed these instructions too:

> If you are running a Rust event please add it to the [calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com) to get it mentioned here. Please remember to add a link to the event too. Email the [Rust Community Team](mailto:community-team@rust-lang.org) for access.

But I didn't get a reply to the email I sent about 3 weeks ago. What should I do? Thanks!

**Comment by nellshamrell** [comment]
Hi @ojeda! Go ahead and email the community team again. I am on that alias and will make sure it gets a response :)

**Comment by ojeda** [comment]
Done! Thanks!

**Review by mariannegoldin — COMMENTED** [review]
Thank you so much for submitting this PR and letting us know about the calendar issue. I will roll this update into our weekly events PR update, and will keep this PR open for now to serve as the team's reminder about the calendaring question.

**Comment by mariannegoldin** [comment]
We have added this to the issue via another PR, closing this PR in lieu of that.

**Comment by ojeda** [comment]
> and will keep this PR open for now to serve as the team's reminder about the calendaring question.

I got an email from Jan-Erik, so I assume this can be closed (though it was closed before that).

**Pull request closed without merging**
