### PR TITLE
Release announcement for `rust-libp2p v0.52.0`

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hi there! The draft for this week hadn't been published yet when you added this link, but it now has been published! Would you like me to pull your link into a different PR and close this one, or would you like to update your PR to include the link in the correct draft?

**Comment by thomaseizinger** [comment]
> Hi there! The draft for this week hadn't been published yet when you added this link, but it now has been published! Would you like me to pull your link into a different PR and close this one, or would you like to update your PR to include the link in the correct draft? 

It would be great if you could add the link to the correct draft, thanks!

**Comment by bennyvasquez** [comment]
Done! Thank you so much.

**Comment by thomaseizinger** [comment]
> Done! Thank you so much.

Thanks for sorting it!

**Pull request closed without merging**
