### PR TITLE
Added Rust-Edu Workshop announcement

### PR DESCRIPTION
**Pull request by BartMassey**
Put this in *Miscellaneous* for lack of a more obvious target. Happy to move it as advised.

Thanks much for TWIR!

### CODE REVIEW

**Comment by ericseppanen** [comment]
Thanks for the content!

The formatting of this is different to our usual convention for the "Community" section; the usual syntax is a one-line list-item link, e.g.
```
* [Rust Education Workshop 2022 Call For Participation](https://rust-edu.org/workshop/)
```
... The CI is failing for this PR because it contains multiple duplicate links.

I'm unsure whether events sometimes get special treatment, or where we should put a link to a "Call for Participation" as it's both a community link and an event. @nellshamrell could you weigh in?

**Comment by BartMassey** [comment]
To be clear, I'm fine with whatever convention you folks think best. Thanks for looking at this!

**Comment by nellshamrell** [comment]
Hi Bart! We strongly prefer contributors make the necessary formatting changes. Apologies for not responding earlier, do you mind re-submitting this for next week's issue with it formatted as @ericseppanen suggests above? It sounds like a really cool workshop!

**Comment by BartMassey** [comment]
Will do. It looks like next week's draft isn't ready to edit yet?

**Comment by nellshamrell** [comment]
Upon second thought…we can get this in this week. For some reason I do not seem to be able to re-open this PR, one sec

**Comment by ericseppanen** [comment]
I added this to the community PR; sorry for the confusion!

**Comment by BartMassey** [comment]
Thanks very much! The extra week will be really helpful given the Workshop format.

**Pull request closed without merging**
