### PR TITLE
Add my P99 CONF talk video to the miscellaneous section

### PR DESCRIPTION
**Pull request by obi1kenobi**
I gave a conference talk on how query optimizations in cargo-semver-checks work, and how they made it more than 2000x faster than before.

Supersedes #4830.

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hi friend! This looks like a super interesting talk, but isn't rust-centric enough for TWiR. Thanks for sharing, and for all you do!

**Comment by obi1kenobi** [comment]
Thanks for reviewing it. Of course your editorial decisions are yours to make, and I will respect whatever decision you make here.

However, I kindly ask that you reconsider on the basis of the following:
- The subject of the talk is how a Rust query engine made a semver-linter for Rust 2000x+ faster via careful API design. There is significant discussion of the challenges specific to Rust, like the instability of the rustdoc JSON format. Aside from the briefest mention of how a comparable design decision was handled in Go, no other programming language is even mentioned in the talk.
- The work covered in the talk is a follow-up of work previously featured in TWiR, whose inclusion I believe you reviewed and approved: https://github.com/rust-lang/this-week-in-rust/pull/4030 — that same work [won an "Exemplary" flair on r/rust](https://www.reddit.com/r/rust/comments/10w73is/speeding_up_rust_semverchecking_by_over_2000x/). 
- P99 CONF even lists my talk under their Rust section: https://www.p99conf.io/

Based on this, it is my opinion that the talk is Rust-centric and on a topic that would be (and has already been) of substantial interest to the Rust community. Of course, if you feel differently despite the above, I respect that the decision is yours to make.

**Comment by cdmistman** [comment]
after further discussion this seems like it's pretty relevant to the Rust community and TWiR readers. thank you @obi1kenobi for your contribution!

**Comment by obi1kenobi** [comment]
Thank you for looking into it and reconsidering, I appreciate it! ❤️

**Pull request merged**
