### PR TITLE
Adds Way of Rhea release

### PR DESCRIPTION
**Pull request by MasonRemaley**
Added to misc, let me know if anything should be tweaked!

### CODE REVIEW

**Comment by cdmistman** [comment]
Hi @MasonRemaley - very neat game, thank you! will add it to my list, i love puzzle games!

thank you for your pr, but unfortunately we do prefer content highlighted in the Community section to be more Rust-focused. while it's very cool that your game was written in Rust, we'd like to hear about that part more - but the format can be anything! as an example or idea, an interview or a blog post discussing the challenges and unique insights you gained while working on this game in Rust would be great!

**Comment by MasonRemaley** [comment]
No worries, that makes sense!

I just did [an AMA](https://www.reddit.com/r/rust_gamedev/comments/1cwqcfl/i_spent_6_years_developing_a_puzzle_game_in_rust/) on the rust_gamedev subreddit--would that be more relevant? Lots of long answers there, I have a habit of writing essays in response to AMA questions haha.

**Comment by cdmistman** [comment]
that would definitely be cool and would be enough for the misc section, but if it's ok i'd also like to challenge you - you have a lot of really neat, well-thought answers in that AMA, but with AMAs imho it can be difficult to distill exactly what's front-of-mind for the person answering questions. i (and i believe readers as well) would love to read a blog post where maybe you aren't covering all the information from the AMA, but you're discussing your experience in a more "distilled" format if that makes sense

again, i'll totally include the AMA next week if you open the PR, but I think a blog post or *some other form of content* where you dictate the actual content would be more meaningful and impactful for readers

**Comment by MasonRemaley** [comment]
I'll be writing up a post mortem eventually, but I'm a bit busy with managing the launch and want to wait 3-6 months so I have more sales data to analyze.

In the mean time, I could meet you in the middle--howbout I write up a "highlights" post with curated & edited snippets from the AMA? I think that'd be a more interesting read than the reddit thread, and I was thinking of spending some time on that over the weekend anyway.

**Comment by cdmistman** [comment]
sounds great! i look forward to it :)

**Pull request closed without merging**
