### PR TITLE
Add project: pg-extras-rs

### PR DESCRIPTION
**Pull request by pawurb**

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hi there! Thanks so much for sharing this. This looks like it's just a link to the repository. Do you have a link that's related to a specific release, or perhaps a blog post about how you develop this project or challenges you have overcome when developing?

**Comment by pawurb** [comment]
Hi. I've recently released this version: https://crates.io/crates/pg-extras/0.6.0 , will it work?

**Comment by bennyvasquez** [comment]
Looking over previous versions of the newsletters, it looks like other editors have allowed just links to github repos to indicate updates, so I've merged this one in. Thank you!

**Comment by pawurb** [comment]
Thanks!

**Pull request merged**
