### PR TITLE
Add TWIR 570 events - non-virtual (in person by continent)

### PR DESCRIPTION
**Pull request by mariannegoldin**
Adding events to #570 - non-virtual. Paired with PR #6042

### CODE REVIEW

**Comment by mariannegoldin** [comment]
For review by @bdillo

**Comment by mariannegoldin** [comment]
@bdillo ready for review

**Comment by mariannegoldin** [comment]
I made some tweaks to the virtual section (formatting, and moving an event into the section that was mis categorized)

**Comment by bdillo** [comment]
> @bdillo ready for review

lgtm! No approver perms yet though 😅

**Pull request merged**
