### PR TITLE
Add a "Papers and Research Projects" section

### PR DESCRIPTION
**Pull request by skade**
This PR adds a new "Paper and Research Projects" section where authors can present their projects. As all other sections, these are titles and links.

For this weekend, I'm volunteering to do all the work for y'all: you post links in the comments below and I will add them to this PR, up to the next edition.

### CODE REVIEW

**Comment by xldenis** [comment]
Hey! I just saw this floating by on twitter, here's the implementation of my PhD thesis work: https://github.com/xldenis/creusot. I'm working on deductive verification for Rust programs, allowing users to write contracts / invariants and have them automatically checked! Plenty of work left to do though 😅.

**Comment by skade** [comment]
@xldenis following the work is half of the fun!

**Comment by mwillsey** [comment]
Cool idea! I'm the lead author of [egg](https://egraphs-good.github.io/), a Rust library for e-graphs and equality saturation. The project just recently won _Distinguished Paper_ at POPL 2021 (where many people asked about Rust), and it will also be my PhD thesis work :)

The [egg webpage](https://egraphs-good.github.io/) has links to papers, videos, and other projects that are using egg in domains like floating point accuracy, 3D CAD, deep learning, and others. The [docs](https://docs.rs/egg/0.6.0/egg/tutorials/) have a nice tutorial/blog post (a la dtolnay) explaining how these techniques help build more effective optimizers, synthesizers, or verifiers by storing and operating over massive sets of equivalent terms.

**Review by nellshamrell — APPROVED** [review]
Thank you!

**Pull request merged**
