### PR TITLE
Rust LWN articles

### PR DESCRIPTION
**Pull request by ojeda**
As usual, I will add more as they come out during the week, if any.

Thanks!

### CODE REVIEW

**Comment by ojeda** [comment]
The first one is not a full article, but there was some discussion nevertheless about the blog post. Not sure what the editors' policy on those, so I am adding a note here. Thanks!

**Review by mariannegoldin — APPROVED** [review]
Thank you!

**Comment by ojeda** [comment]
You're welcome!

**Comment by ericseppanen** [comment]
In the future I don't think we should include links to articles that just link to something else. Our preference is to just link to the original source. There are many places hosting comments about articles; we don't generally provide additional links for that reason.

**Comment by ojeda** [comment]
Thanks for the details! Yeah, that makes sense, and I suspected something like that could be the policy already, which is why I added the note above. At least in this case the author of the blog post wrote a comment in LWN, linking to another post, so hopefully someone found it valuable nevertheless.

**Pull request merged**
