### PR TITLE
C/QotW and notable changes

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by llogiq** [comment]
Weird. I have no idea why that markdown check fails. My local check works fine, and I don't see any problem with the syntax.

**Comment by bennyvasquez** [comment]
The error (noting for future benny, just in case)

``` ##[debug]Evaluating condition for step: 'inspect_markdown'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: inspect_markdown
##[debug]Loading inputs
##[debug]Loading env
Run python3 tools/inspect_markdown.py --num-recent 5
  python3 tools/inspect_markdown.py --num-recent 5
  shell: /usr/bin/bash -e {0}
##[debug]/usr/bin/bash -e /home/runner/work/_temp/c9798b5b-[2](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:2)e7e-4798-9b8[3](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:3)-37b2[5](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:5)92858[6](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:6)a.sh
recent files: ['content/2022-10-26-this-week-in-rust.md', 'content/2022-11-02-this-week-in-rust.md', 'content/2022-11-0[9](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:9)-this-week-in-rust.md', 'content/2022-[11](https://github.com/rust-lang/this-week-in-rust/actions/runs/3526464139/jobs/5915164330#step:5:11)-16-this-week-in-rust.md', 'draft/2022-11-23-this-week-in-rust.md']
warnings exist:
draft/2022-11-23-this-week-in-rust.md: empty <li> tag after <code>str.contains(&amp;str)</code>
Error: Process completed with exit code 1.
##[debug]Finishing: inspect_markdown ```

IMO that doesn't make sense, given that we don't have li tags in anything. I'm gonna merge it and see if it continues to fail on future checks.

**Comment by bennyvasquez** [comment]
@llogiq I did some testing on a branch I used to add our mastodon link, and this is the line that it's choking on when building the HTML. I removed the line from the draft, but is there another way we can phrase the title that is still accurate but won't cause problems? If you can give me that info, I'll get it added back in for tomorrow's draft. 

`* [remove HRTB from `[T]::is_sorted_by`{,`_key`}](https://github.com/rust-lang/rust/pull/102977)`

**Comment by llogiq** [comment]
That's really weird; squiggly brackets shouldn't do anything in those link titles. I wonder if it chokes on the `[T]` or the `{,`. If it's the former, replacing `[T]` by `slice` would do the trick. If it's the latter, `[T]::is_sorted_by(_key)` (in backticks) should work.

Or we can simply leave it out.

**Comment by bennyvasquez** [comment]
Ended up doing both to make it work, but I got it included! 

* [remove HRTB from `slice::is_sorted_by`(`_key`)](https://github.com/rust-lang/rust/pull/102977)

**Pull request merged**
