### PR TITLE
Add blog post about trademark policy

### PR DESCRIPTION
**Pull request by ijackson**

### CODE REVIEW

**Comment by cdmistman** [comment]
Hi Ian, thank you so much for contributing! I think this is better placed under the `Miscellaneous` section as historically our `Observations/Thoughts` section has been used for technical posts. If you can please move the link to the respective section then this PR is all set to be merged!

**Comment by nellshamrell** [comment]
Publishing editor for this week here, I'll go ahead and make the change since I want to get this published tonight.

**Review by nellshamrell — APPROVED** [review]
Ty!

**Comment by ijackson** [comment]
Hi.  I was AFK.  Obviously I'm happy to have it moved, and thanks for taking care of tht!

**Pull request merged**
