### PR TITLE
Add observations/thoughts: Rustls benchmarking update

### PR DESCRIPTION
**Pull request by cpu**
Hi folks - this is my first this week in rust update. Hope I've matched the expected format correctly :stars: 

Thanks for maintaining the newsletter.

### CODE REVIEW

**Comment by bennyvasquez** [comment]
hi @cpu, and welcome! The formatting is perfect. :) This one I would probably put in either Thoughts/Observations or in Misc. The updates section is typically for tooling releases. Do you want to pick one and move it over, or would you feel more comfortable if I did?

**Comment by cpu** [comment]
> This one I would probably put in either Thoughts/Observations or in Misc.

Aha! Thanks for the guidance. I've moved it into Thoughts/Observations.

**Comment by bennyvasquez** [comment]
Perfect. resolved a merge conflict, and you're all set. Thank you again!

**Comment by cpu** [comment]
Thanks!

**Pull request merged**
