### PR TITLE
Add RustTalk

### PR DESCRIPTION
**Pull request by jiacai2050**

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hi @jiacai2050, this certainly looks cool! Unfortunately, I'm not personally able to review it.  @MATRIXKOO and @Folyd do you mind giving part of it a quick listen and letting me know what you think?

If those reviewers approve, I would be happy to include this in next week's issue.

**Review by PsiACE — APPROVED** [review]

**Review by Folyd — APPROVED** [review]
LGTM

**Comment by MATRIXKOO** [comment]
This is an interview with a Rust database engineer who worked in PingCap. I think the interview is Ok.No Ads.

**Review by MATRIXKOO — CHANGES_REQUESTED** [review]
Need deal with the conflict.

**Comment by jiacai2050** [comment]
Ooops, After merge with master, it seems a lot commit

**Comment by jiacai2050** [comment]
PTAL @MATRIXKOO @nellshamrell

**Review by nellshamrell — APPROVED** [review]
Ty!

**Pull request merged**
