### PR TITLE
Add misc blog post: 'Declaring Holy Cyber War on Web Scrapers Using R…

### PR DESCRIPTION
**Pull request by ginger51011**
…ust'

I am completely open to alternative titles, if this is seen as inappropriate (perhaps: `pandoras_pot: Crashing Undesired Web Scrapers`? Not the same punch though...)

I also was not sure where to put this, so I put it in _Misc_. Also open to changes there

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hi @ginger51011 - that is a cool article, but I would definitely prefer a different title. "pandoras_pot: Crashing Undesired Web Scrapers" does work, though I think something along the lines of "Fighting back: Turning the Tables on Web Scrapers Using Rust" would also work.

Would you be open to updating the title of the article?

**Comment by ginger51011** [comment]
> Hi @ginger51011 - that is a cool article, but I would definitely prefer a different title. "pandoras_pot: Crashing Undesired Web Scrapers" does work, though I think something along the lines of "Fighting back: Turning the Tables on Web Scrapers Using Rust" would also work.
> 
> Would you be open to updating the title of the article?

Yeah sure, I can do that! Give me a minute, that suggestion was great

**Comment by ginger51011** [comment]
> Hi @ginger51011 - that is a cool article, but I would definitely prefer a different title. "pandoras_pot: Crashing Undesired Web Scrapers" does work, though I think something along the lines of "Fighting back: Turning the Tables on Web Scrapers Using Rust" would also work.
> 
> Would you be open to updating the title of the article?

Done!

**Comment by nellshamrell** [comment]
Ty so much!

**Pull request merged**
