### PR TITLE
Add final links 453

### PR DESCRIPTION
**Pull request by andrewpollack**

### CODE REVIEW

**Comment by andrewpollack** [comment]
Thank you!

**Comment by ericseppanen** [comment]
What was the origin of this "move data out of closure" article? It seems really vague and confusing to me...

**Comment by andrewpollack** [comment]
> What was the origin of this "move data out of closure" article? It seems really vague and confusing to me...

This came from a compilation of Twitter links, reviewed/added as part of the publishing steps

**Comment by ericseppanen** [comment]
I don't see how that article makes for useful reading for... anyone, really. I would have declined to add it.

**Comment by andrewpollack** [comment]
Apologies I did not meet the bar on vetting articles. @nellshamrell thoughts on next steps?

**Comment by nellshamrell** [comment]
It was submitted on Twitter, I don't think it's a problem that we included it. It could be useful to someone who is working through a similar problem.

**Pull request merged**
