### PR TITLE
fixes create email script

### PR DESCRIPTION
**Pull request by nellshamrell**

### CODE REVIEW

**Comment by andrewpollack** [comment]
Pushed changes to this PR to shift all publishing shebangs to be bash

**Review by andrewpollack — APPROVED** [review]

**Review by mariannegoldin — APPROVED** [review]
LGTM!

**Comment by cdmistman** [comment]
I'm sorry I'm a little confused why this PR is open. What was broken with /bin/sh? /bin/sh should exist on all unix-compatible systems, but /bin/bash isn't guaranteed to do so (due to licensing). i understand we're using an ubuntu docker image but want to make sure i understand the problem :)

**Comment by andrewpollack** [comment]
@nellshamrell was running into issues with using `source file.sh` over the WSL of Linux, and resolution was to update this shebang. I dont have the hardware to confirm that this was independent of the issue, and will need to defer explanation beyond this

**Comment by nellshamrell** [comment]
it did not work on WSL, and when I changed it it did work, that is my best explanation :)

**Comment by nellshamrell** [comment]
Just confirmed that is still the case on my system - this appears to be necessary for use with WSL

**Pull request merged**
