### PR TITLE
Add `fcp` v0.2.1 release announcement

### PR DESCRIPTION
**Pull request by Svetlitski**

### CODE REVIEW

**Review by nellshamrell — CHANGES_REQUESTED** [review]
Hello there!

Thank you for opening this pull request.  We generally are not looking for links to crates or GitHub repos without some sort of context. We would much rather you submit a blog post introducing your project and how a Rust user might use it (and what it would help them do) and/or what you learned about Rust in the process of writing the project. Would you be willing to write up some sort of post - perhaps also highlighting the changes in this new release?

**Comment by Svetlitski** [comment]
> Hello there!
> 
> Thank you for opening this pull request. We generally are not looking for links to crates or GitHub repos without some sort of context. We would much rather you submit a blog post introducing your project and how a Rust user might use it (and what it would help them do) and/or what you learned about Rust in the process of writing the project. Would you be willing to write up some sort of post - perhaps also highlighting the changes in this new release?

Sure, perhaps I could get this into the 7/28 newsletter since the 7/21 one has already been released. While I don't have a blog, [the repo's `README`](https://github.com/Svetlitski/fcp#fcp) gives a thorough overview of what `fcp` does and why you would want to use it, includes [benchmark results](https://github.com/Svetlitski/fcp#benchmarks) demonstrating its high-performance, and also discusses [the strategies used to achieve this performance](https://github.com/Svetlitski/fcp#methodology). Alternatively I could link to the [0.2.1 release page](https://github.com/Svetlitski/fcp/releases/tag/v0.2.1), which as you suggest discusses the highlights and other changes made in this release.

**Comment by Svetlitski** [comment]
I've linked directly to the [0.2.1 release page](https://github.com/Svetlitski/fcp/releases/tag/v0.2.1) this time. Let me know if you'd prefer for me to link to the `README` instead, for the reasons mentioned in my previous comment.

**Comment by nellshamrell** [comment]
Thanks so much! Because there are so many rust projects out there, I'm looking for something with more content (beyond the project README page and the release page) in order to highlight it in the newsletter.

Here's another thought - are you interested in getting contributions from the community on the current open issues in your repo? We could highlight those in the "Call for Participation" section of This Week in Rust, which is another way to highlight your project.

**Comment by Svetlitski** [comment]
> Thanks so much! Because there are so many rust projects out there, I'm looking for something with more content (beyond the project README page and the release page) in order to highlight it in the newsletter.
> 
> Here's another thought - are you interested in getting contributions from the community on the current open issues in your repo? We could highlight those in the "Call for Participation" section of This Week in Rust, which is another way to highlight your project.

Not really, no. There's not much to be done at the moment. Forgive my confusion, as I announced the last release of the project in This Week in Rust [issue 398](https://this-week-in-rust.org/blog/2021/07/07/this-week-in-rust-398/#:~:text=fcp%200.2.0%20released%20-%20a%20significantly%20faster%20alternative%20to%20cp) with a link to just the repo itself, but I understand if that was just an editorial oversight. All I was really trying to accomplish here was to introduce more people to a useful tool, and let existing users of `fcp` know that it has gotten even more efficient than it already was. Regardless of whether or not this is included, for the sake of the newsletters's health I question valuing "blog posts" more highly than direct links to a project, as this places the emphasis on form rather than content (example: [a blog post with _much_ less detail than your average README](https://sixtyfps.io/blog/introducing-cargo-ui.html) from TWiR [issue 400](https://this-week-in-rust.org/blog/2021/07/21/this-week-in-rust-400/#:~:text=cargo-ui%3A%20introducing%20cargo-ui%2C%20a%20gui%20for%20cargo)). All questions aside, as a reader of the newsletter I appreciate all the work you put into editing TWiR, and look forward to reading future issues.

**Comment by nellshamrell** [comment]
Hello again!

The reason I included the link to your repo in issue 398 was because the README had so much content and I felt it provided a lot of context for the project and why someone might want to use it (that's why I didn't ask you to write up a blog post at that time). If I compare the README at the time of the [0.2.0 release](https://github.com/Svetlitski/fcp/tree/2b23b093632b9d7f8fdf327b04583ea10730d9c1) with the one for the [0.2.1 release](https://github.com/Svetlitski/fcp), they have not changed too much (other than some fixes and the addition of the badges) . Including a link that showed the README of the repo again would be re-posting a lot of the same content (something we have done by accident before and have been criticized for).

While it is possible to link directly to the release page for 0.2.1, I don't feel that is enough content in it for it to be included in the newsletter.  There are so many crates being updated every week it's not tenable to include them all (particularly for minor releases), this is the reason I require more content - sometimes through more explanations, examples, etc. in the release notes or in a separate blog post.

I fully admit I have not always applied this standard consistently. Editing a newsletter like this requires a lot of judgement calls - and those judgement calls often change over time as the community's (and my own) context evolves. With the example that you cite from issue #400, that was the announcement of the crate, rather than a minor release of the tool. That's why I made the decision to include it. It's not the form (blog post vs. README) that determines whether or not something is included, it's the content within it and whether that content has been featured before.

I hope this provides some more insight into my thought process around including releases of crates in This Week in Rust.

**Comment by Svetlitski** [comment]
This definitely provides a lot of insight into the criteria for inclusion in the newsletter, and clears up the questions I had. Thank you for taking the time to explain all of this, and for all the effort that goes into editing TWiR. Hope you have a pleasant evening.

**Comment by nellshamrell** [comment]
Thank you so much for reading TWiR and being a part of the Rust community! :)

**Pull request closed without merging**
