### PR TITLE
Mention new lrpeg crate for left recursive peg grammars

### PR DESCRIPTION
**Pull request by seanyoung**
Signed-off-by: Sean Young <sean@mess.org>

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hi @seanyoung! Thanks for submitting this, it looks really cool! Do you mind writing up a blog post or something that would provide a little more context than the GitHub repo?

If you check out our README, we list this as a thing we are not generally looking for:
```
Links to crates or GitHub repos without some sort of context. We would much rather you submit a blog post introducing your project and how a Rust user might use it (and what it would help them do) and/or what you learned about Rust in the process of writing the project.
```

Would you mind writing up a blog post or something similar for this project?

**Comment by nellshamrell** [comment]
You could also consider adding more context to the README and perhaps link to write ups with more context, [this pull request is a good example](https://github.com/rust-lang/this-week-in-rust/pull/1905)

**Comment by seanyoung** [comment]
@nellshamrell thanks for the feedback. Now the link goes to a blog post, and I've expanded the readme. Any feedback or suggestions you have are very welcome.

**Comment by nellshamrell** [comment]
This looks great! Thank you!

**Comment by nellshamrell** [comment]
I added this in using [this commit](https://github.com/rust-lang/this-week-in-rust/commit/4857b475894cdc2b3e5fff497eab27d6754d14b4). Had to do this because of some file name conflicts (which were my fault, not yours). Thanks for submitting this!

**Pull request closed without merging**
