### PR TITLE
cargo-show-asm 0.1.20

### PR DESCRIPTION
**Pull request by pacak**
A maintained `cargo-asm` alternative, closest thing I have to a blog post.

### CODE REVIEW

**Comment by bennyvasquez** [comment]
Hi again! This looks really useful but doesn't quite fit the rust-centric guidelines that we're looking for. We'd love to see more about how this is coded, and what you learned in the process of doing it.

**Comment by pacak** [comment]
Hmm... It's a useful tool, not a guide, I haven't learned anything new, but the link had some implementation details - calling cargo and all that. Every previous post I looked at had rust-analyzer changelog with even less implementation details and "what you learned in the process". :shrug:

**Comment by nellshamrell** [comment]
Hi @pacak! I'm the lead editor of This Week in Rust. This does, indeed, look like a very useful tool and you've done the right thing by posting it on the Rust subreddit. Due to the volume of outstanding Rust projects being created every day, we have had to put in place some more strict standards for what we include in TWiR and what we don't. This is in no way intended to diminish your work but we do require some more content in order to include projects in TWiR. If you'd like to talk about this more, I'm happy to talk 1:1.

**Comment by pacak** [comment]
@nellshamrell I was mostly going off amount of feedback varying between [thank you for this tool](https://www.reddit.com/r/rust/comments/xmsbl7/cargoshowasm_0120_new_and_improved_all_over_the/ipqqjx9/) and [this should be included in cargo itself](https://www.reddit.com/r/rust/comments/xmsbl7/cargoshowasm_0120_new_and_improved_all_over_the/iptltw0/). People [who might actually use it](https://github.com/pacak/cargo-show-asm/watchers) will [find about it eventually](https://mobile.twitter.com/burntsushi5/status/1528807196309573635), it's already popping up [here](https://teletype.in/@bminaiev/reproducible-benchmarks#4NxK) and [there](https://youtu.be/lRV_5IBUTes?t=550). But there are still guides out there that refer to `cargo-asm` which depending on a situation either [no longer works at all](https://www.reddit.com/r/rust/comments/xmsbl7/cargoshowasm_0120_new_and_improved_all_over_the/ipxrnht/) or [works very slow](https://github.com/gnzlbg/cargo-asm/issues/241) and [affects your project](https://github.com/gnzlbg/cargo-asm/issues/239) until `cargo clean` after use that so I was trying to save those who still use `cargo-asm` some frustration.

Tool itself is as rust-centric as it gets and the guide can be summarized to "if you want to see asm rustc generates - use this".

I'm happy to talk more as well here or manpacket gmail.com about this, but I don't see myself writing a "today I learned" style of post - because I didn't or "how this works" - because it's not a rocket science, it's just asking `cargo` to ask `rustc` to emit a `.s`/`.ll`/`.mir` file and parsing/presenting it coupled with a bunch of boring platform specific tweaks like [horrors of doing crypto stuff on MacOS](https://github.com/pacak/cargo-show-asm/pull/51) or [cross platform `glob` crate is not really cross platform on windows](https://github.com/pacak/cargo-show-asm/pull/2).

**Pull request closed without merging**
