### PR TITLE
Add an article to Observations/Thoughts

### PR DESCRIPTION
**Pull request by rbehjati**
Hi! I've added an article that I recently wrote to the Observations/Thoughts section.

### CODE REVIEW

**Comment by rbehjati** [comment]
Many thanks. I have resolved the conflict.

**Comment by rbehjati** [comment]
@mariannegoldin I just noticed that is omitted from the final version. Should I create another PR, to include it in the next week's edition?

**Comment by mariannegoldin** [comment]
@rbehjati my apologies - this fell off in a merge conflict reconciliation. I will take the step to add it to #542. Thank you for bringing this to my attention!

**Comment by rbehjati** [comment]
No worries. Thanks for the great work, and thanks for adding it to 542 :)

**Comment by mariannegoldin** [comment]
@rbehjati I opened a new PR #5364 to get this into TWIR 542.

**Pull request merged**
