### PR TITLE
Add cargo-mutants

### PR DESCRIPTION
**Pull request by sourcefrog**
(The repo linked here has some detailed description.)

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hello there! Did you mean to add this to [the draft for this week](https://github.com/rust-lang/this-week-in-rust/blob/master/draft/2022-02-16-this-week-in-rust.md)?

**Comment by sourcefrog** [comment]
Yes, I probably let it linger and missed the cutoff. Will rebase.
Martin

**Comment by sourcefrog** [comment]
Should be good now. Please take another look @nellshamrell?

**Review by nellshamrell — APPROVED** [review]
Looks good, ty!

**Pull request merged**
