### PR TITLE
Add Otter release announcement

### PR DESCRIPTION
**Pull request by ijackson**
Hi.  I hope this is sufficiently interesting and Rusty to be worthy of This Week In Rust.

Thanks :-).
Ian.

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hello there!

Thanks for submitting this. I'm assuming the project is written in Rust, but I'm not seeing any references to Rust in the documentation or any links to the source code. Do you mind adding content about why you chose Rust and what you learned about Rust in the process of writing it? It does look very cool!

**Comment by ijackson** [comment]
Hi.  Thanks for looking at my suggestion.

The blog post does have a link to the source code but it's under "Installation and usage" so not all that obvious.  To be honest I should have expected your question!

I have just pushed a commit here, adding a separate link to that part of the build instructions, to my proposed bullet point for This Week In Rust.  The build instructions do contain some of discussion of the security issues of dependency management cargo-style, but it's very much written to address an outsider to the Rust community, rather than a Rustacean.

> Do you mind adding content about why you chose Rust and what you learned about Rust in the process of writing it? It does look very cool!

Thanks.  I don't think it would make sense to kind of retrospectively add that to my release announcement blog post.  If you feel these links are, even put together, not sufficiently much of interest to the wider Rust community, then I understand.  In that case, perhaps I would find time to make a more Rust-focused blog post about Otter, but no promises!

Regards,
Ian.

**Comment by ijackson** [comment]
I should also mention that the Rust crates which comprise most of Otter are on crates.io, but really only to make sure they're visible to crater etc. - it's not really useful to treat them as Rust libraries.

**Review by nellshamrell — APPROVED** [review]
That works! Thank you!

**Pull request merged**
