### PR TITLE
Rust for Linux LWN articles

### PR DESCRIPTION
**Pull request by ojeda**
A couple of articles (which became freely available recently) and some others for which I asked LWN for permission to use subscriber links.

### CODE REVIEW

**Comment by ojeda** [comment]
Added two more that got published since then.

**Comment by ojeda** [comment]
Added one more from today.

**Comment by ojeda** [comment]
One more I noticed in today's "newly freed" reminder.

**Review by cdmistman — COMMENTED** [review]
wow, so many interesting articles, all very good reads :D 

however, I'm concerned about a 'flood' of lwn articles appearing this week 😅 I'll approve this, with the caveat that I might remove some articles depending on what the edition looks like. I also think a couple of articles are in the wrong section, so that will help :)

**Comment by ojeda** [comment]
It is due to all the related conferences being together in September and the fact that I didn't have time to submit this every week while I was traveling -- it is not something expected every week.

If there is a limit of articles from a single source or something like that, we could put the older ones and next week newer ones, for instance.

**Pull request merged**
