### PR TITLE
Added lifetimekata

### PR DESCRIPTION
**Pull request by tfpk**
Should have added this a little while ago, but it's had a couple updates and I figure it's useful to put here now rather than never :)

### CODE REVIEW

**Comment by nellshamrell** [comment]
This looks really cool!

We generally do not include direct links to github repos (there are so many awesome Rust related projects coming out each week and we cannot include them all), though we do sometimes make exceptions for a README that reads like a blog post.

Would you be willing to either write up a blog post or flesh out the README more? You could include information about why you created this, what inspired it, how it can help others learn Rust, etc.

**Comment by tfpk** [comment]
Hey! I've changed the link to the gitbook rather than the github link. It's more a teaching resource than a "project" in the sense I think you mean; but I see the rationale so hopefully the link change fixes things :)

**Comment by nellshamrell** [comment]
Awesome! Since we already published last week's issue, do you mind moving it to the new draft?

**Comment by bennyvasquez** [comment]
@tfpk it looks like this is still committed to last week's edition. Want to give this another try? If you'd rather, I can just include it in my PR when I am working on this week's issue tomorrow.

**Comment by tfpk** [comment]
Moved to #4029 thanks :)

**Pull request closed without merging**
