### PR TITLE
Update deps in order to fix #2732

### LINKED ISSUE #2732: Layout broken due to missing stylesheet
A stylesheet isn't loaded on any page I tried. The HTML source contains these:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="/">
```

The first one works, the second one is broken.

It seems that the `ASSET_URL` in [this line](https://github.com/rust-lang/this-week-in-rust/blob/master/themes/rusted/templates/base.html#L37) isn't defined. I looked in the git history, but there weren't any changes that could have caused this problem as far as I can tell.

P.S. sorry for reporting this 1 day before Christmas. Don't feel obliged to fix this in this year, and enjoy the holidays :)

### PR DESCRIPTION
**Pull request by Aloso**
Fixes #2732

I tested it, but please double-check that this didn't break any functionality.

### CODE REVIEW

**Comment by nellshamrell** [comment]
Thanks so much, @Aloso! Taking a look now.

**Review by nellshamrell — APPROVED** [review]
I had to add `libsass==0.21.0` to requirements.txt, but other than that this did the trick! Thank you SO MUCH for looking into this, I really appreciate it!

**Comment by Aloso** [comment]
You're welcome, and thank you for your help!

**Pull request merged**
