### PR TITLE
`CFP` from hyperswitch for issue 488

### PR DESCRIPTION
**Pull request by NishantJoshi00**
Adding some good first issues from our open source initiative, [`Hyperswitch`][hyperswitch]. This is our first time calling for participation, looking forward to hearing from the community.

[hyperswitch]: https://github.com/juspay/hyperswitch

### CODE REVIEW

**Comment by andrewpollack** [comment]
Thank you! Pulling in our CFP expert @bennyvasquez

**Comment by bennyvasquez** [comment]
Hi there! First, thank you so much for your submission. The last issue listed here looks like it's not a rust-centric request. We'd love to include the first two for sure, but I don't seem to be able to edit your PR. If you want to re-submit with just the first two, or help me understand how the last one is, in fact, rust-centric, feel free!

**Comment by NishantJoshi00** [comment]
Hey @bennyvasquez, should I edit this PR and make the changes you requested? Or has this revision is already published?

**Comment by NishantJoshi00** [comment]
This is a rough explanation of the last issue, let me know if this can qualify as a valid issue for the CFP:
- In this Issue, the contributor is required to implement domain types for as mentioned card number, or any other mechanism which can allow static validation of the card information to be embedded into type conversions. We were looking for some implicit mechanism that we can use as an abstraction for such validations.

Hope this helps! Please, leave feedback on your thoughts so, I can re-submit the CFPs. Thanks!

**Comment by NishantJoshi00** [comment]
Hey again :wave: , for that issue we are looking to write abstractions in rust itself, our entire project currently only comprises of safe rust, and we aren't looking for any of the `ffi` just yet. I hope that clearifies things. This task was specified under the refactoring to introduce domain types in the codebase.

**Comment by bennyvasquez** [comment]
AH! Perfection. Rather than make you re-submit I've added your links to [my fork for next week's draft](https://github.com/bennyvasquez/this-week-in-rust/tree/cfp_489) myself. Feel free to ping me (here or on [mastodon](https://social.linux.pizza/@benny) or on [twitter](https://twitter.com/bennyvasquez)) if anything changes for you!

**Comment by NishantJoshi00** [comment]
That's great! Thanks a lot.

**Pull request closed without merging**
