### PR TITLE
C/QotW + notable changes

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by llogiq** [comment]
No idea why the markdown check fails. Perhaps someone can help?

**Comment by ericseppanen** [comment]
> No idea why the markdown check fails. Perhaps someone can help?

I will have a look.

**Comment by ericseppanen** [comment]
The error is because of this line:
```
* [implement `[OsStr]::join`](https://github.com/rust-lang/rust/pull/96881)
```

That should be valid markdown, except that Python-Markdown <= 3.3.6 doesn't parse it correctly, which results in an empty list-item in the output, instead of the link we asked for.

This was seen previously as #2781. Since it would silently show up broken on the site, I added a CI check for empty list-items in the output.

I see that Python-Markdown 3.3.7 has been released (which *I think* should have the fix), but until we get that integrated into the site deployment workflow, my workaround is to add a useless `&nbsp` to the offending line, i.e.
```
* [implement `[OsStr]::join`](https://github.com/rust-lang/rust/pull/96881) &nbsp;
```

**Comment by nellshamrell** [comment]
Doing the workaround for now, but will take a look at upgrading (ty for the pull request!) later this week

**Pull request merged**
