### PR TITLE
Introducing MOTW!

### PR DESCRIPTION
**Pull request by slyons**
After seeing the discussion pop up a few times on Reddit, I thought I'd take a stab at establishing a new weekly series, Module of the Week! It's totally original and not at all based on PyMOTW at all.

I've taken a bit of a story-based approach with this as I've found it helps relate concepts and puts some structure around the examples.

I've used some very search-friendly headers so it does have a bit of a cookbook feel but I hope to dig a bit deeper than most cookbook samples do.

This is a PR for content mostly, I'm going to have the full example code in a separate repo ready to go before publishing.

Really looking forward to any feedback that anyone could provide!

### CODE REVIEW

**Comment by nellshamrell** [comment]
Looks pretty cool! Are you planning on publishing this out of your own repo?

**Comment by slyons** [comment]
Thanks for the feedback! I put it as another article within the TWIR repo to keep the look and feel consistent (plus everything was already set up). I'll publish it from within my own repo  until something better or more community friendly comes along :)

**Comment by slyons** [comment]
So it's been a couple of days, but I've finally got [MOTW](https://motw.rs/) up and running, backed by [this repo](https://github.com/slyons/rust-module-of-the-week).

I've updated Pelican, spun out the Theme into a separate repo and built a Docker image for building the docs in a consistent environment. If any of those are interesting I could open a separate PR.

**Comment by nellshamrell** [comment]
@slyons I would love if you would open a separate PR!

**Comment by slyons** [comment]
> @slyons I would love if you would open a separate PR!

I did last week and will do so again this week!

**Pull request closed without merging**
