### PR TITLE
Events 459

### PR DESCRIPTION
**Pull request by andrewpollack**

### CODE REVIEW

**Review by mariannegoldin — COMMENTED** [review]
May wish to add to Virtual events: 
9/13/22
https://www.meetup.com/opentechschool-berlin/events/288032274/

**Comment by mariannegoldin** [comment]
May wish to roll in the change proposed by this PR: #3615

**Comment by andrewpollack** [comment]
Good eye on the Berlin event, as well as carrying the previous PR. Added both!

**Comment by mariannegoldin** [comment]
Looks great, approving!

**Pull request merged**
