### PR TITLE
Added video Audio adventures in Rust: UI with Actix, WebView, and React

### PR DESCRIPTION
**Pull request by Lakret**
Thank you :)

### CODE REVIEW

**Review by nellshamrell — CHANGES_REQUESTED** [review]
I'm currently seeing "An error occurred. Please try again later." when accessing that link. Do you mind confirming?

**Comment by nellshamrell** [comment]
Oh...I hear that YouTube is having an outage, that is likely what is going on.

**Comment by Lakret** [comment]
@nellshamrell Yup, it was down when you were checking this out, apparently. I guess I can just submit it to the next issue, right?

**Comment by nellshamrell** [comment]
We will definitely get this in next week's issue!

**Review by nellshamrell — APPROVED** [review]

**Pull request merged**
