### PR TITLE
Rust for Linux LWN articles

### PR DESCRIPTION
**Pull request by ojeda**
A couple more this time -- all freely available now.

### CODE REVIEW

**Comment by ojeda** [comment]
Added a third, also from LWN, though not exactly a "Project/Tooling Update", unless we consider LWN a "project" giving an update on Rust -- so please feel free to move it where it may make more sense.

Thanks!

**Comment by mariannegoldin** [comment]
Thank you for the submission. The last article seems better suited for "Observations". I will move it there.

**Review by mariannegoldin — APPROVED** [review]
Approved with formatting tweak and re-arranging between sections.

**Comment by ojeda** [comment]
My pleasure!

**Pull request merged**
