### PR TITLE
New Zellij version

### PR DESCRIPTION
**Pull request by imsnif**
Hey there,

We just released a new version of Zellij, the Rusty terminal workspace and I'd be very excited to share it with your readers.

Thanks!

### CODE REVIEW

**Review by nellshamrell — APPROVED** [review]
Ty!

**Comment by ericseppanen** [comment]
This link is 404 now. @nellshamrell should we remove it?

**Comment by imsnif** [comment]
> This link is 404 now. @nellshamrell should we remove it?

Sorry about this! We just deployed a new version of the site that erased it. I'm fixing it now

**Comment by imsnif** [comment]
Fixed. Sorry again - we're having some issues with our site CI

**Pull request merged**
