### PR TITLE
Add link to Why Associated Type

### PR DESCRIPTION
**Pull request by ifsheldon**
Add link to Why Associated Type, which is my thought on the design of Associated Type. It's not about How, but Why, so I'd rather like to place it under Thoughts, not Walkthroughs.

### CODE REVIEW

**Comment by nellshamrell** [comment]
@MATRIXKOO, @Folyd could you help me review this one?

**Comment by Folyd** [comment]
Hi, @ifsheldon. Thanks for the PR. I strongly recommend you submit one PR of **Rust Why** after the book is finished instead of multiple PRs each with a single article.

**Comment by ifsheldon** [comment]
I don't think that is gonna work. I still have multiple articles to write, some of which may not be submitted to TWiR. And a bundle of articles is just too long to read. The article is self-contained, so there's no context tightly related to the book/ article collection itself.

**Review by Folyd — APPROVED** [review]

**Review by nellshamrell — APPROVED** [review]
Ty!

**Pull request merged**
