### PR TITLE
Add `Adding a Rust compiler frontend to GCC`

### PR DESCRIPTION
**Pull request by mfrw**
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

### CODE REVIEW

**Comment by ericseppanen** [comment]
There's probably no need to send PRs for things that show up on the front page of HN or get a lot of attention on Reddit or Twitter. The editors scan all of those places already :)

**Comment by mfrw** [comment]
:( my bad .. I thought of adding as I had not seen a PR already.
Sure, feedback noted ... Will refrain from subsequent PRs

**Comment by ericseppanen** [comment]
No problem; we know that the current system can be a bit confusing, as editors don't usually post a PR until quite late in the week.

**Comment by nellshamrell** [comment]
Your contribution is appreciated nonetheless! If you want to be sure we see something, it's ok to open a PR.

**Comment by nellshamrell** [comment]
Looks like we got this in another pull request, but thank you again for making sure it was brought to our attention!

**Pull request closed without merging**
