### PR TITLE
Added Hyperswitch Issues to 2023-10-18-this-week-in-rust.md

### PR DESCRIPTION
**Pull request by VedantKhairnar**

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
@cdmistman 
Sorry for being late in the addition.
Can you pls allow these additions?

**Comment by cdmistman** [comment]
Hi Vedant, unfortunately we don't allow adding content to the week's draft after we've shared [the draft publicly](https://x.com/ThisWeekInRust/status/1712297154436354405). I'd be happy to include it next week though!

**Comment by VedantKhairnar** [comment]
Hey, 
No worries. Thanks for your response.
Will add these changes to the upcoming draft. : )
.
Also, This-Week-in-Rust has been very helpful to our organisation.
Apart from raising a weekly PR, what other means can I contribute to TWiR?

**Comment by VedantKhairnar** [comment]
Hey @cdmistman 
Removed the direct addition from last time as had added it in my prev commit and 
as well added the new content for the upcoming TWiR.
Please let me know if any changes are needed.
Thanks.

**Review by U007D — APPROVED** [review]
Thank you, @VedantKhairnar!

**Pull request merged**
