### PR TITLE
2024 edition aprooval

### PR DESCRIPTION
**Pull request by gorentbarak**
The 2024 edition was approved! Added this to the list of approved RFCs.

### CODE REVIEW

**Comment by gorentbarak** [comment]
Sorry, my tags file added a lot.

**Comment by bennyvasquez** [comment]
Hi there! It looks like the tags file is still in this PR. Would you mind updating the PR to exclude it? Thank you!

**Comment by gorentbarak** [comment]
Of course!

**Comment by gorentbarak** [comment]
There! I removed the tags file.

**Comment by bennyvasquez** [comment]
Thank you so much!

**Pull request merged**
