### PR TITLE
binary tree implementation walkthrough blog post

### PR DESCRIPTION
**Pull request by anupj**
New walkthrough blog post

### CODE REVIEW

**Review by mariannegoldin — APPROVED** [review]
Interesting example and walkthrough, thank you. Approved.

**Comment by mariannegoldin** [comment]
Going to update this PR to isolate just the addition of the blog post. It seems some of the other changes may be relating to other PRs.

**Review by mariannegoldin — APPROVED** [review]
Did a manual rebase/merge conflict resolution - approved and merged. Thank you!

**Comment by anupj** [comment]
Thank you @mariannegoldin 🙏🏽

**Pull request merged**
