### PR TITLE
Add this week in Databend 36 & 37

### PR DESCRIPTION
**Pull request by PsiACE**
Ty!

---

### Analyzing Nginx Logs with Databend and Vector

Systems are producing all kinds metrics and logs time by time, do you want to gather them and analyze the logs in real time?

Databend provides [integration with Vector](https://databend.rs/doc/integrations/vector), easy to do it now!

You can use Databend to analyze Nginx access logs in just four steps:

1. Deploy Databend, Create a Database and a Table for Nginx logs, Create a User for Vector Auth
2. Install and Configure Nginx
3. Install and Configure Vector, Run it
4. Generate Nginx logs and Analyze them in Databend

To learn more about how to implement it, check out [Analyzing Nginx Logs with Databend and Vector](https://databend.rs/doc/learn/analyze-nginx-logs-with-databend-and-vector).

### CODE REVIEW

**Comment by ericseppanen** [comment]
This issue was already released; can we put this in the new draft issue?

**Comment by ericseppanen** [comment]
This issue was already released; can we put this in the new draft issue?

**Comment by nellshamrell** [comment]
I agree with @ericseppanen - because the issue was already released, let's put this in the draft of next week's issue (even if that means we have two weeks of This Week in Databend in next week's issue). I generally publish each newsletter on Wednesday evening US Pacific time and, while I have allowed for last minute additions in the past, I'd like to stop that practice.

**Comment by PsiACE** [comment]
thanks @ericseppanen & @nellshamrell . 

I totally agree with you guys. Let's meet with it in the next week.

**Comment by PsiACE** [comment]
Ty! It's great to share our progress with the community. In addition to some features and improvements, we've also worked on driver support and, of course, announced a project for performance monitoring.

---

### Databend Performance Data Collection and Visualization

Late last week, we proudly launched the <https://perf.databend.rs/>. This is a website for monitoring the performance of Databend's nightly releases.

Databend Performance Data

The current performance data consists mainly of:
- A set of numerical computation SQLs for evaluating the performance of in-memory vectorization engines, based on Databend's numbers table function providing ten billions data.
- A common set of SQLs for air traffic analysis, based on the publicly available OnTime dataset from the U.S. Department of Transportation, 60.8 GB of CSV data, 202687654 records.

**Review by nellshamrell — CHANGES_REQUESTED** [review]
Ty!

**Pull request merged**
