### PR TITLE
Added "Nine rules of elegant Rust library APIs" using the free link

### PR DESCRIPTION
**Pull request by CarlKCarlK**
[Added "Nine rules of elegant Rust library APIs" using the free link](https://github.com/rust-lang/this-week-in-rust/commit/111081986fde92d7f815d8e08e0b96c6a7771c67)

### CODE REVIEW

**Comment by ericseppanen** [comment]
Is the "friend's link" necessary? The URL without it seems to work fine for me on various browsers, and I don't see any evidence that the site is limiting page views or anything like that...

**Comment by CarlKCarlK** [comment]
I believe that without it, people who have read more than 3 articles in the month will be paywalled. Most people would be fine.

**Comment by ericseppanen** [comment]
This particular article doesn't seem to have limited access to non-members. You can verify this by looking at the site main page; only articles with a ★ have that limitation.

**Comment by CarlKCarlK** [comment]
Cool! (Maybe because I’m not making money from Medium.)

**Comment by CarlKCarlK** [comment]
The shorter link is fine then

From: Carl ***@***.***>
Sent: Saturday, June 18, 2022 4:49 PM
To: ***@***.***>
Subject: RE: [rust-lang/this-week-in-rust] Added "Nine rules of elegant Rust library APIs" using the free link (PR #3375)

Cool! (Maybe because I’m not making money from Medium.)

**Review by nellshamrell — APPROVED** [review]
Ty!

**Pull request merged**
