### PR TITLE
Build front-end web apps with Yew and WebAssembly in Rust

### PR DESCRIPTION
**Pull request by zzy**
- Build front-end web apps with Yew and WebAssembly in Rust -part 3: Assets & Refactor
- Build front-end web apps with Yew and WebAssembly in Rust -part 4: GraphQL data & Parsing

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hi @MATRIXKOO  and @Folyd - do you mind reviewing these ones? I really appreciate this!

**Comment by MATRIXKOO** [comment]
sure.Working on it.

**Comment by Folyd** [comment]
Hi @zzy, thanks for your PR. I am afraid I disagree to merge this. Please see my issue #2099. 

I'd recommend [Rust Chinese Magazine](https://rustmagazine.github.io/rust_magazine_2021/), which is a better place to meet your Chinese audiences. Feel free contribute to that. Here is the repo: https://github.com/RustMagazine/rust_magazine_2021

**Comment by zzy** [comment]
@Folyd @nellshamrell I had removed all ads from blog.budshome.com.

**Review by MATRIXKOO — COMMENTED** [review]
Good. No more Ads.

**Comment by nellshamrell** [comment]
Since ads have been removed, I will go ahead and merge this.

**Pull request merged**
