### PR TITLE
add a script to inspect links and report problems

### LINKED ISSUE #2378: Detect duplicate or malformed links
It would be useful to be able to detect:
- link URLs that are malformed (e.g. missing the "https://" part of the url)
- link URLs that show up twice in one issue.
- links that have shown up in previous issues.

The goal would be to have something that can be run in CI.

Inspired by #2352.

### PR DESCRIPTION
**Pull request by ericseppanen**
This is a first draft, for review/comments/etc. Fixes #2378.

This script checks for malformed and duplicated links. The goal would be
to run it in CI to save the editors from the job of noticing that a link
isn't formatted correctly, or was submitted multiple times.

Some notes:
- I wasn't sure where in the tree to put this new python script. For the moment, I just created a subdirectory `tools`.
- The general strategy is to use the python `markdown` module to format each `.md` file, and then use `bs4` to parse the resulting html and extract links.
- Some parts of the document always contain duplicate links, so right now the script also parses html heading tags and only scans the links within specific "sections". This is a little fragile because it requires the list in this script to match what's actually in the issues. Alternatively, it could have a list of URLs that are always ignored?
- Sometimes identical links don't look identical because they have tracking metadata attached (e.g. `?utm_source=reddit`, etc.) so I strip those. That's also a little fragile, and requires an allowlist of sites that need http parameters (e.g. youtube). Maybe this was a dumb idea to begin with, and it would have been simpler to just leave the links alone.
- At present it will report issues on all inspected files. If we don't want to go back in time and fix those issues, we may need some date-threshold that allows errors in old files to not be reported.

For anyone who's curious how often duplicate links occur, here is the output of the script against the last 40 issues:
```text
possible duplicate link adventures.michaelfbryan.com/posts/ffi-safe-polymorphism-in-rust/ in file content/2020-12-16-this-week-in-rust.md (also found in content/2020-12-16-this-week-in-rust.md
possible duplicate link www.abetterinternet.org/post/memory-safe-tls-apache/ in file content/2021-02-10-this-week-in-rust.md (also found in content/2021-02-03-this-week-in-rust.md
possible duplicate link blog.logrocket.com/macros-in-rust-a-tutorial-with-examples/ in file content/2021-02-24-this-week-in-rust.md (also found in content/2021-02-03-this-week-in-rust.md
possible duplicate link blog.stephenmarz.com/2021/02/22/writing-pong-in-rust/ in file content/2021-03-17-this-week-in-rust.md (also found in content/2021-03-10-this-week-in-rust.md
possible duplicate link jduchniewicz.com/posts/2021/02/c-to-rust-or-how-to-render-your-mindset/ in file content/2021-03-17-this-week-in-rust.md (also found in content/2021-03-03-this-week-in-rust.md
possible duplicate link youtube.com/playlist?list=PLfllocyHVgsRwLkTAhG0E-2QxCf-ozBkk in file content/2021-04-07-this-week-in-rust.md (also found in content/2021-02-24-this-week-in-rust.md
possible duplicate link blog.jetbrains.com/rust/2021/04/08/intellij-rust-updates-for-2021-1/ in file content/2021-04-14-this-week-in-rust.md (also found in content/2021-04-07-this-week-in-rust.md
possible duplicate link blainehansen.me/post/red-blue-functions-are-actually-good/ in file content/2021-04-28-this-week-in-rust.md (also found in content/2021-04-21-this-week-in-rust.md
possible duplicate link ferrous-systems.com/blog/gdb-and-defmt/ in file content/2021-05-05-this-week-in-rust.md (also found in content/2021-05-05-this-week-in-rust.md
possible duplicate link blog.knoldus.com/why-rust-for-embedded-development/ in file content/2021-05-19-this-week-in-rust.md (also found in content/2021-05-12-this-week-in-rust.md
possible duplicate link youtu.be/Ys7ma3au5m0 in file content/2021-05-19-this-week-in-rust.md (also found in content/2021-05-12-this-week-in-rust.md
possible duplicate link redpoll.ai/blog/imm-with-rv-12/ in file content/2021-05-26-this-week-in-rust.md (also found in content/2021-05-19-this-week-in-rust.md
possible duplicate link plume.benboeckel.net/~/JustAnotherBlog/designing-rust-bindings-for-rest-ap-is in file content/2021-06-09-this-week-in-rust.md (also found in content/2021-06-02-this-week-in-rust.md
possible duplicate link adventures.michaelfbryan.com/posts/deserializing-binary-data-files/ in file content/2021-06-30-this-week-in-rust.md (also found in content/2021-06-23-this-week-in-rust.md
possible duplicate link www.cmyr.net/blog/keypaths.html in file content/2021-06-30-this-week-in-rust.md (also found in content/2021-06-23-this-week-in-rust.md
possible duplicate link oswalt.dev/2021/06/polymorphism-in-rust/ in file content/2021-06-30-this-week-in-rust.md (also found in content/2021-06-23-this-week-in-rust.md
possible duplicate link cprimozic.net/blog/speeding-up-webcola-with-webassembly/ in file content/2021-07-07-this-week-in-rust.md (also found in content/2021-06-16-this-week-in-rust.md
possible duplicate link jbarszczewski.com/rust-tauri-svelte-tutorial in file content/2021-07-21-this-week-in-rust.md (also found in content/2021-07-14-this-week-in-rust.md
possible duplicate link dev.to/mapoulos/rust-first-thoughts-7l0 in file content/2021-08-04-this-week-in-rust.md (also found in content/2021-07-28-this-week-in-rust.md
possible duplicate link blog.jetbrains.com/rust/2021/08/04/what-s-new-in-intellij-rust-for-the-2021-2-release-cycle/ in file content/2021-08-10-this-week-in-rust.md (also found in content/2021-08-04-this-week-in-rust.md
possible duplicate link blog.guillaume-gomez.fr/articles/2021-07-29+Interacting+with+data+from+FFI+in+Rust in file content/2021-08-10-this-week-in-rust.md (also found in content/2021-08-04-this-week-in-rust.md
possible duplicate link owengage.com/writing/ in file content/2021-08-18-this-week-in-rust.md (also found in content/2021-07-28-this-week-in-rust.md
```

### CODE REVIEW

**Comment by nellshamrell** [comment]
This is cool! I will take a look either this weekend or early next week!

**Comment by ericseppanen** [comment]
I was bothered by the fragile handling of query parameters in the first commit, so I added another commit that inverts the logic. Now there is a list of known tracking parameters. If tracking parameters are found, a warning is raised. This is somewhat opinionated (tracking bad!) so I can drop the warning if the TWIR editors prefer.

The way urllib works also has a nice side-effect: we can warn on URLs that have weird properties like an empty anchor (`http://example.com/#`) or empty query parameters (`http://example.com/?`), showing the suggested canonical form with those bits stripped off.

**Comment by nellshamrell** [comment]
Thank you! I haven't had a chance to look at this in depth yet, but I will when I am able! I really appreciate you continuing to add to this :)

**Comment by ericseppanen** [comment]
> Thank you! I haven't had a chance to look at this in depth yet, but I will when I am able! I really appreciate you continuing to add to this :)

No problem! :)

**Comment by ijackson** [comment]
@ericseppanen Thank you for doing this. It kept bothering me when I saw the TWIR editors making manual fixups to my anomalous syntax etc.

> I was bothered by the fragile handling of query parameters in the first commit, so I added another commit that inverts the logic. Now there is a list of known tracking parameters. If tracking parameters are found, a warning is raised. This is somewhat opinionated (tracking bad!) so I can drop the warning if the TWIR editors prefer.

+1 to dropping tracking parameters.  And, yes, probably a list of known-bad ones is correct.

**Comment by ericseppanen** [comment]
I made a change that makes the "strict" check apply to the entire "Updates from Rust Community" section, instead of having to name all the subsections individually.

("strict" means we will inspect all links found in this section; non-strict means no checking is done.)

**Comment by nellshamrell** [comment]
Hi @ericseppanen! I finally have time to turn my attention back to this. I've checked out this branch and have tried to run the script with

```bash
$ python3 tools/inspect_links.py 
```

However, I get this error:

```bash
Traceback (most recent call last):
  File "tools/inspect_links.py", line 10, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
```

Should there be a requirements.txt file for this script?

**Comment by ericseppanen** [comment]
I'm not sure what the right way to express this is, but `bs4` is [Beautiful Soup](https://pypi.org/project/beautifulsoup4/).

`pip install beautifulsoup4` is how I installed it.

**Comment by ericseppanen** [comment]
I am able to run the script in a clean container (ubuntu 20.04 running python 3.8) with the following requirements:
```txt
beautifulsoup4==4.10.0
Markdown==3.3.5
```
I'm not sure whether this should be a standalone file in the `tools` directory, or be merged into the repo root (where the Markdown version is much older)...

**Comment by nellshamrell** [comment]
I would put it in the tools directory for now

**Comment by ericseppanen** [comment]
I silenced warnings on old issues by default, which is desirable for CI.

**Comment by luisvonmuller** [comment]
That awesome, thanks.

**Pull request merged**
