### PR TITLE
Revert "add search" removal, fixing email publishing

### PR DESCRIPTION
**Pull request by andrewpollack**
Reverting rust-lang/this-week-in-rust#4075 revert.
Restores @ndd7xv 's fantastic search PR https://github.com/rust-lang/this-week-in-rust/pull/3942, and patches with #4077 to address reason of revert.

* Only use search plugins for website styling, removing from email styling
* Adds new variable `TESTING_LOCALLY` to ease URL adjustments
* Renames `TWIR_NEWSLETTER_THEME ` variable to `USE_EMAIL_THEME` to reflect usage in config

### CODE REVIEW

**Comment by ndd7xv** [comment]
Small nitpick, but `TWIR_NEWSLETTER_THEME` is still [referenced in the README under to build the newsletter](https://github.com/rust-lang/this-week-in-rust#to-build-the-newsletter)! 

Updating this to `USE_EMAIL_THEME` might be helpful for people who may want to make changes to the newsletter (or people who want to check if their PRs break the newsletter because they previously made PRs that had to be reverted oop)

**Review by nellshamrell — APPROVED** [review]
Looks excellent! Feel free to merge, then deploy changes to the github pages site when you are ready!

**Comment by andrewpollack** [comment]
> Small nitpick, but `TWIR_NEWSLETTER_THEME` is still [referenced in the README under to build the newsletter](https://github.com/rust-lang/this-week-in-rust#to-build-the-newsletter)!

Good spot @ndd7xv ! There are a few things I want to update to make the publishing workflow easier to follow, and I'll create a quick PR for this

**Comment by andrewpollack** [comment]
#4083 captures the updated instructions for building the newsletter

**Pull request merged**
