### PR TITLE
Add link to the Rust official survey 2023

### PR DESCRIPTION
**Pull request by apiraino**
Also cc @Kobzol for a quick revision of the text.

thanks!

### CODE REVIEW

**Comment by Kobzol** [comment]
Text looks good, although I don't recall seeing such text in TWiR (usually there are just links to official Rust blog posts). Let's see what TWiR editors think :)

**Comment by nellshamrell** [comment]
Hello! Ty for submitting this! We generally only include links, rather than descriptive text, but we would be happy to include both the link to the blog post and the link to the survey.

**Comment by apiraino** [comment]
@nellshamrell better now?

**Comment by andrewpollack** [comment]
Thank you!

**Pull request merged**
